name: Build Documentation

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - uses: nikeee/docfx-action@master
      with:
        args: docfx.json
    
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: root
        server: 148.251.126.19
        #port: # default is 22
        # you can copy private_key from your *.pem file, keep format
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        # will put all file under this path
        local_path: ./_site/* # default is ./*
        # files will copy to under remote_path
        remote_path: /var/www-betadocs # default is /
        # sftp args
        # args: # optional
